### PR TITLE
makes SDK compliant with JakartaEE

### PR DESCRIPTION
**Pull request by manishT72**
Build from OAS 3.0.1

## BREAKING CHANGES

* Makes Xero-Java SDK compliant with JakartaEE. 
* Changes order of Idempotency key parameter in method definitions
* Fixes method definitions where required request-body parameters were declared as optional.
    Following methods will have required body parameters now
    * **Payroll-AU**
      - updateEmployee
      - updatePayRun
      - updatePayslip
      - updateSuperfund
      - updateTimesheet
    * **Files**
      - uploadFile
      - updateFile
      - uploadFileToFolder
      - createFileAssociation
      - createFolder
     * **Bankfeeds**
      - createStatements
     * **Assets**
      - createAssetType

## Release Notes

- JavaEE has moved to JakartaEE. All future features will be introduced to Jakarta namespaces. Many of the famous frameworks and web servers have already accepted the move. See the details [here](https://jakarta.ee/blogs/javax-jakartaee-namespace-ecosystem-progress/)
- This change would require partner apps to upgrade to newer frameworks and web servers to work with JakartaEE.

### Features:

1. [354](https://github.com/XeroAPI/Xero-Java/issues/354) Request for Jakarta platform compliant Xero SDK
2. Updates the OpenAPI specifications to reflect Warnings from the API response for Payments.

### Bug Fixes:

1. [357](https://github.com/XeroAPI/Xero-Java/issues/357) Error when trying to use the Xero java API on Spring Boot / Java 17

### CODE REVIEW

**Review by Raghunath-S-S-J — APPROVED** [review]

**Review by Raghunath-S-S-J — APPROVED** [review]

**Comment by emeraldhieu** [comment]
Can you push this to Maven Central for use? I'm migrating to Spring Boot 3 and it failed with the error "NoClassDefFoundError: javax/ws/rs/core/UriBuilder"

**Comment by Devin-RC** [comment]
> Can you push this to Maven Central for use? I'm migrating to Spring Boot 3 and it failed with the error "NoClassDefFoundError: javax/ws/rs/core/UriBuilder".

@emeraldhieu there's a 5.0.0-alpha version on Maven Central that fixes the `NoClassDefFoundError`. We are currently using that for the time being until a stable release is available.

**Comment by hieu-nguyen-multiplier** [comment]
@Devin-RC dev
I've tried using 5.0.0-alpha and got compilation errors due to missing `com.xero.models.accounting.CurrencyCode`.

**Comment by emeraldhieu** [comment]
@Devin-RC dev
I've tried using 5.0.0-alpha and got compilation errors due to missing `com.xero.models.accounting.CurrencyCode`.

**Comment by Devin-RC** [comment]
@emeraldhieu I just checked and I'm able to use the `com.xero.models.accounting.CurrencyCode` enum on version 5.0.0-alpha. It surely isn't missing. Maybe you could try cleaning and rebuilding the project?

**Comment by emeraldhieu** [comment]
> @emeraldhieu I just checked and I'm able to use the `com.xero.models.accounting.CurrencyCode` enum on version 5.0.0-alpha. It surely isn't missing. Maybe you could try cleaning and rebuilding the project?

@Devin-RC I got this build error. I run `.gradlew clean test`.

How did you check it?
```
app/src/main/java/com/mycompany/core/mydomain/adapters/xero/XeroContactDTOMapper.java:57: error: cannot find symbol
        if (currencyCode == com.xero.models.accounting.CurrencyCode.EMPTY_CURRENCY || currencyCode == null) {
                                                                   ^
```

Revert to a stable version works. What's wrong with the alpha version?

**Comment by Devin-RC** [comment]
@emeraldhieu After a bit of digging around, you can find that the empty enum values you're referring to have actually been removed from the Accounting specification from [Release 4.30.1](https://github.com/XeroAPI/Xero-Java/releases/tag/4.30.1). It is mentioned in the release notes.

You can find the exact commit diff [here](https://github.com/XeroAPI/Xero-Java/pull/360/files#diff-d24f23dee3a8fe2a2379d42037d924f768356149afc50ee174eb67914929076e).

> Reverting to a stable version works. What's wrong with the alpha version?

From the [issue](https://github.com/XeroAPI/Xero-Java/issues/362) you've raised, I see you're using 4.29.1. The latest stable release is 4.30.1. I believe the 5.0.0-alpha release is based on the latest stable release, which is why it doesn't contain the enum you're looking for.

It seems that if you want to upgrade the SDK version (to resolve the JakartaEE compliance issue), you'll have to refactor your code to not refer the removed `CurrencyCode.EMPTY_CURRENCY` enums.

**Comment by erdi** [comment]
Is there a roadmap for a stable 5.0.0, please? Is it days, weeks or months maybe? I'm upgrading a project using `com.github.xeroapi:xero-java` as a dependency to Jakarta EE 9 so I'm affected by the issue this PR is fixing.

**Comment by erdi** [comment]
FWIW, [it looks like 5.0 has now been released](https://github.com/XeroAPI/Xero-Java/releases/tag/5.0.0). 🚀

**Pull request merged**
