### PR TITLE
New report endpoints

### PR DESCRIPTION
**Pull request by slouc-spotcap**
Added endpoints for fetching various types of reports. 

As you can see, I'm using sbt; we could either omit this from the PR or you can adopt it and add sbt to your list of supported build tools (note that jitpack is not needed).

### CODE REVIEW

**Comment by SidneyAllen** [comment]
Hi @slouc-spotcap 

Thanks for the pull request.  I'll review the reports improvements - appreciate you contributing back.

Love that you're looking to support sbt - but we can't remove the pom.xml file.  I'm using it to build and deploy this as a branch for maven users.  The pom.xml file also defines the other dependencies like the google oauth lib and the xero-accounting-api-schema which we need.

Is there anyway to have both a sbt and pom in the repo?   Sorry for my ignorance on the subject - I'm not too familiar with sbt.

**Comment by slouc-spotcap** [comment]
I'm not suggesting to remove pom.xml (perhaps you saw my commit where I removed it, but I added it back later). I'm pretty sure they can co-exist and not bother each other.

**Comment by SidneyAllen** [comment]
@slouc-spotcap - ok - thanks for clarifying - yes I was looking at your commit where you removed it.
I'll give it a once over before merging.  Thanks again.

**Comment by SidneyAllen** [comment]
Tested all the new methods for Reports - looks good.

**Comment by SidneyAllen** [comment]
@slouc-spotcap can you drop me a note (sid.maestre@xero.com) with your physical mailing address and  your T-Shirt size.  We've got a little something we want to send your way ;-)

**Pull request merged**
